#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Load custom environment setup scripts & aliases
# --> Sources all files in $HOME/.zpreszto-contrib that are not directories
if [ -x $HOME/.zprezto/custom ]; then
	for file in $HOME/.zprezto/custom/*.sh ; do
		source $file
	done
fi

#
# Automatically load any work-specific configs
#
if [ -x $HOME/work-zsh/ ]; then
  for file in $HOME/work-zsh/*.sh ; do
    source $file
  done
fi

#
# Implement 'set & save' for prompt themes
#
autoload -Uz promptinit
promptinit
prompt $PROMPT_THEME

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
