#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Load custom environment setup scripts & aliases
# --> Sources all files in $HOME/.zpreszto-contrib that are not directories
if [ -x $HOME/.zprezto/custom ]; then
	for file in $HOME/.zprezto/custom/*.sh ; do
		source $file
	done
fi

#
# Implement 'set & save' for prompt themes
#
autoload -Uz promptinit
promptinit
prompt $PROMPT_THEME

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
